const state = {
  layers: [[/* assise 0 */]],
  currentLayer: 0,
  selectedSize: "M50_entire",
  hoverPoint: null,
  jointThickness: 0.012,
  rotationY: 0,
  whiteBricks: false,
  deleteMode: false,
  moveMode: false,
  rotateMode: false,
  projectTitle: "",
  layerboxPos: { x: 60, y: 360 },
  titleInputPos: { x: window.innerWidth / 2 - 150, y: 50 },
  history: [{ layers: [[/* assise 0 */]], projectTitle: "" }],
  historyIndex: 0,
  selectedBrick: null,
  ghostBrick: null,
};